[ssl]
certificate = "domain.crt"
key = "domain.key"

[resources]
memory_limit = -1 # in bytes, -1 for ignore memory limit

[rest-server]
ip = "0.0.0.0"
port = 3333
ssl = true

[websocket-server]
ip = "0.0.0.0"
port = 3131
ssl = true

[listener-alpha]
type = "template"
ip = "0.0.0.0"
port = 7777

[listener-delta]
type = "template"
ip = "0.0.0.0"
port = 4444

[whitelist]
aniko = "aniko"
unity = "unity"
