[ssl]
certificate = "domain.crt"
key = "domain.key"

[resources]
memory_limit = -1 # in bytes, -1 for ignore memory limit

[client-server]
ip = "0.0.0.0"
port = 3333
ssl = false

[listener-alpha]
type = "default"
ip = "0.0.0.0"
port = 7777

[whitelist]
aniko = "aniko"
